language: python
python:
  - '3.6'
install:
  - pip install pipenv
  - pipenv install
before_script:
  - pipenv run python manage.py migrate
  - pipenv run python -m spacy download pt_core_news_sm
script: pipenv run python manage.py test
